### PR TITLE
Adding ODT example to storybook and fixing variorum bugs

### PR DESCRIPTION
**Pull request by ajolipa**
### In this PR
- Fixes bug in variorum mode where folios in different documents with the same `folioID` were not being stored properly in the component state: when in variorum mode, folios are now stored internally with the ID `[documentID]_[folioID]` to avoid collisions;
- Updates the `viewportState` function to track the associated document of the currently selected folio, so that if you navigate back to the grid view from a folio in variorum mode, the document that folio came from will be automatically selected;
- Updates Storybook to use the ODT project as the example for the variorum feature

### CODE REVIEW

**Comment by ajolipa** [comment]
Update: Now also addresses Issue #118 by removing the blue highlighting from the "current folio" in grid mode.

**Comment by ajolipa** [comment]
Further update: Now includes a fix to the resizing functionality of the split pane view so that it now works with touchscreen devices as well as mouse clicks.

**Comment by ajolipa** [comment]
Further update: Now also includes a trigger to reload the document data in the case that the component props change without the user navigating to a new page. (See PR #123 )

**Review by NickLaiacona — APPROVED** [review]
Looks good! 🚀

**Pull request merged**
