### PR TITLE
NPM package

### PR DESCRIPTION
**Pull request by camdendotlol**
# Summary

- updates the entry JS to export the `EditionCrafter` component itself, rather than a configuration object
- replaces the live static page with Storybook
  - if you need to use the `EditionCrafter` component on a non-React website such as a Hugo app, it should be relatively simple: https://react.dev/learn/add-react-to-an-existing-project#using-react-for-a-part-of-your-existing-page
- checks in `package-lock.json` (not checking it in is a recipe for disaster when you're publishing to npm)
- updates the package name to use the `@performant-software` scope
- adds a GitHub workflow - literally copy/pasted from `edition-crafter-cli` so I'm pretty confident it will work!
- replaces the ancient and abandoned `react-font-awesome-5` package with `react-icons`
  - this was part of my troubleshooting for an issue I came across - it didn't fix the issue but as this package was a drop-in replacement, I think it's reasonable to keep the change!

### CODE REVIEW

**Comment by NickLaiacona** [comment]
This all looks good, but I would like to keep the UMD build distribution, for users that don't want to add React to their website. The idea is to have it generate both a React Component and a UMD build.

**Comment by camdendotlol** [comment]
Based on what I know about packaging, I think it's going to be difficult to include both a component and a UMD version in the same package.

If we're keeping the [same UMD API as before](https://github.com/cu-mkp/editioncrafter/blob/main/__tests__/integration/editioncrafter/index.html#L16), we need to include React in the exported `js` file. But we **can't** bundle React when exporting a component for use in other React apps, as the bundled React would conflict with the instance used in the project that imports the component. (We use `peerDependencies` instead, see [@performant-software/semantic-components](https://github.com/performant-software/react-components/blob/master/packages/semantic-ui/package.json) for an example.)

My proposal for supporting both is to keep two packages, `editioncrafter` (the plain UMD version that works the same as before) and `editioncrafter-react` (the React component version). It would take a bit of configuration magic to set everything up, but I think it would be doable.

Alternatively, we could keep the build process as it is in this PR, which makes it only slightly more complicated to use on a non-React webpage. The downstream website would need to import React and call a few methods in their `script` tag (see https://react.dev/learn/add-react-to-an-existing-project#step-2-render-react-components-anywhere-on-the-page). The code would look something like this:

```js
import { createRoot } from 'react-dom/client';
import EditionCrafter from 'editioncrafter';

// Render your React component instead
const root = createRoot(document.getElementById('viewer'));
root.render(
  <EditionCrafter config={...} />
);
```

**Comment by NickLaiacona** [comment]
Sounds good, having them in different packages makes sense to me. I would like `editioncrafter` to be the React version, perhaps the UMD version is `editioncrafter-umd`. Could https://www.unpkg.com/ be useful for delivering the UMD version?

**Comment by camdendotlol** [comment]
I've used JSDelivr before which is very similar and didn't need any configuration, so I assume Unpkg would be similar. Either (or both) would be trivial to set up.

**Pull request merged**
