### PR TITLE
Three pane view

### PR DESCRIPTION
**Pull request by ajolipa**
### In this PR
Adds a third pane to the viewer, decoupled from the first two panes. 
image
image

### Notes and further work
- Right now there isn't a toggle for this mode; it will just always be on for wide enough screens. Of course a toggle could be added to the UI that shows or hides the third pane, if desired.
- Book mode is kind of broken currently with the third panel; need to think about what we want the book mode behavior to be in this view.
- Right now the default when the viewer loads is to have the third panel basically entirely hidden, able to be revealed by dragging the divider out from the righthand side of the screen. Of course this can be changed to whatever default behavior we end up wanting.
- Should there be other available configurations? E.g. an option to have the second and third pane stacked vertically instead of horizontally, or to have the first pane on top and the latter two in a row underneath? Maybe out of scope but I don't think it would be too hard to create those options (she says naively...).
- Note that this branch is based off the RB-ely-green-multidoc branch, so probably shouldn't be merged until that branch is.

### CODE REVIEW

**Comment by NickLaiacona** [comment]
@ajolipa this is very cool - things seems to mostly behave as I would expect. Would it be possible to make the third pane stay stowed unless I pull it out? Presently, if you adjust the splitter between panes one and two, the third pane pops out. You have to put it back each time you adjust it if you don't want it. 

Another issue is that if you pull the third pane far enough to the left, a blank panel appears to the right of it.

**Review by NickLaiacona — CHANGES_REQUESTED** [review]
Please see my comments regarding the resizing.

**Comment by ajolipa** [comment]
@NickLaiacona See if this most recent push fixed the resizing issues.

**Review by NickLaiacona — APPROVED** [review]
Works pretty well now. 👍

**Pull request merged**
